services:
  postgres:
    image: postgres:15-alpine
    container_name: airline_delays_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-airline_delays}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      TZ: ${TZ:-America/Sao_Paulo}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Data Layer/silver/ddl.sql:/docker-entrypoint-initdb.d/01-schema.sql

  tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    # Removida a palavra 'run' e mantido o resto
    command: tunnel --no-autoupdate --url tcp://postgres:5432
    depends_on:
      - postgres

volumes:
  postgres_data: